# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('interference-pattern',
                                 ['opengym', 'internet', 'mobility', 'config-store', 'lte', 'netanim', 'ns3-ai'])
    obj.source = ["interference-pattern/%s" % s for s in [
                'mygym.cc', 'sim.cc'] ]

